pipeline{
	agent any
	stages{
		stage('Check stage'){
			withMaven(maven : 'MVN'){
		           bat 'mvn --version'
			}
		}
	}
		
	stage('Compile stage'){
			steps{
				withMaven(maven : 'MVN'){
				bat 'mvn -f mvm-math/pom.xml compile'
			}
		}
	}
		stage('Test stage'){
			steps{
			withMaven(maven : 'MVN'){
			 	bat 'mvn -f mvm-math/pom.xml install'			}
		}
	}
		
