pipeline{
	agent any
	
	stages{
		steps ('Check stage'){
			withMaven(maven : 'Mvn'){
		           bat 'mvn --version'
			}
		}
	}
		
	stage('Compile stage'){
			steps {
				withMaven(maven : 'Mvn'){
				bat 'mvn -f mvm-math/pom.xml compile'
			}
		}
	}
		stage('Test stage'){
			steps {
			withMaven(maven : 'Mvn'){
			 	bat 'mvn -f mvm-math/pom.xml install'			
			 	}
		}
	}
}		
