pipeline{
	agent any
	stages{
		stage('Check stage'){
			steps{
		           bat 'mvn --version'
			}
		
		stage('Compile stage'){
			steps{
				bat 'mvn clean compile'
			}
		stage('Test stage'){
			steps{
			 bat 'mvn test'
			}
		}
		}
		}
